language: generic
services:
  - docker
env:
  global:
    - secure: qLWC3p3QH8B7i1vPCMpogV3uX5mf6cF6mjAQpr1QBFFn5rjBNID/TleAPXw3CJ2wc4rSfkfSX6ktrE0MM6qNOCtzTddp0BRbHGwZCRJ5hyNEXcS4KzaDhASzwQaMJZQ7FRnyVCzb7aobYQj6psdfnB6+dh2TJiKbDxW0F8gAiGJBdkfLCG4hOuBWmT6+IMv9coSNzx8L4esyjfXR0T20I57MOni84t9VwFHSsGRKZchMuQOmHMNkyUdWZw7ZC6fo881M9wZ7yRoBci/bdc7MRgB3FddMvtGK5RdghSMwggNjYPxdUpjTEyT1f/+Zsej6L92xYwzHeAfm7YstW/io58Q1QC5MadWnifRda6L4t8R8aJZsJxvJhpjbxhFId0LEjJ3YuyqUTiVsY44IEAnYbmd3GiNrMsGIlKcYu0xzGmj/PY4y1ddxdiQhhvO5ieGFK6x+kwk+szDV7kV6AIiqORYwN7Ea/1dWIzVKmarr5oCxUxUxF8bb33Ri0iAYBSqclMwwB03K2XHx8RSaqGn20KUmE3dx+4jeCjyYPAGdvYZcYHPKDr6iQ0MB+OZrofhRcBNBEYgza5rZVAN5YIDiWQA6APdOoUl0yApyMoM8SWbyzmdXAG9cSsrZFcanxTSfZb7MJxG5e1h/ZPzEbfKNl0FYAk3PA6ZOg/Lt9rlafSY=
    - secure: uz5kfDdBXdsW4SW26B1LL85ug5S2kFNxsEUkSz4+IJxRVbSl+4ORg8ijgt+74HUOy0saRuTAfLXWJUI4X9TbUa9MWdFD9Oc+Iz8t4BrCOw7cXHD7Jqo/7kyGv8eUq/cbSfrfoVW5fm6ISex7wKUOnBTbDim/x58eu7ftdI9GSV/RcPbDooieL5GM1JwiGmh0iUEVLBF9UlhGf9f+JSKNWUn3w9D62yAEnElF1XsscnTsA5AftEVh/YLWBlo9hc+SO8Zu4XCaLqVd6xVKI9wB2Z6ppl7Uv3QmpucNAA2wsFPWck6cmU3nCMdhpBMCDlzmfS9N30aUORfsbFggVFGxmHsEXfY3j+XVLQ5XyPsoZ4Ph24fH6O8tOkuACs+cxK9X7ItTIkKilbX9zQJRNeHL/2tk0n47QZuzgQYb+eXlRr15LvGMmkJq3NPHIHWFo7nkrdt+ZqHbWs/3owAaDILiutC93aNIp96a57X/aoudWHXzZFL81GYAch0WXH6pvbDcdJ8H8ZU4vcmHTqGwvQlZGlkH+V1pVwArGbtTghEIfpsZb+c2d9pGn7JzwXRMmOAmvlSbw3RWqqZ+/yp4R6HzUyHJ0kuVYT6KONgwYhRQJgBSd/DppqJjaLwM7zVrXRL8ID7HaNNRz7W6MZJZ+xYmtEhdrDnJnxUE6BzNEagN2Mc=
script:
  - make docker.build
deploy:
  - provider: script
    skip_cleanup: true
    script: make docker.push
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
